apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: file-interpolation
  title: File interpolation for Sonarqube
  description: scaffolder v1beta3 template demo publishing to PR on existing git repository
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: User input
      required:
        - sonarqube_key
      properties:
        sonarqube_key:
          title: Sonarqube project key
          type: string
          description: Unique Sonarqube project key

  steps:
    #- id: create_file
    #  name: Create Sonarqube project file
    #  action: fetch:plain
      #run: echo "sonar-project-key:" ${{ sonarqube_key }} > scott.txt
   #   input:
    #    targetPath: ./
    #    url: ./scott.txt
      

    - id: directory_contents
      name: Directory Contents
      action: debug:log
      input:
        message: "Hi Scott"
        listWorkspace: true
      
