apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pull-request
  title: Pull Request Action template
  description: scaffolder v1beta3 template demo publishing to PR on existing git repository
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: User input
      required:
        - sonarqube_key
      properties:
        sonarqube_key:
          title: Sonarqube project key
          type: string
          description: Unique Sonarqube project key

  steps:
    - id: create_file
      name: Create Sonarqube project file
      description: Create Sonarqube project file
      run: echo "sonar-project-key:" ${{ sonarqube_key }} > scott.txt
      
    - id: directory_contents
      name: Directory Contents
      description: Print directory contents to verify file creation

