apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: file-interpolation
  title: File interpolation for Sonarqube
  description: scaffolder v1beta3 template demo publishing to PR on existing git repository
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: User input
      required:
        - sonarqube_key
      properties:
        sonarqube_key:
          title: Sonarqube project key
          type: string
          description: Unique Sonarqube project key

  steps:
    - id: create_file
      name: Create Sonarqube project file
      action: catalog:write
      input:
        filePath: ./sonarqube.yml
        entity: sonarqube-key:scott      

    - id: directory_contents
      name: Directory Contents
      action: debug:log
      input:
        message: "Hi Scott"
        listWorkspace: TRUE
      
